language: node_js

node_js:
  - 10
  - 12
  - node

before_install:
  - npm install -g npm@6

script:
  - npm run test:ci

cache:
  directories:
    - node_modules

jobs:
  allow_failures:
    - node_js: node

